env:
  PROJECT_ID: enterity
  SERVICE_NAME: enterity-API

steps:
   - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:latest" .
